INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Riku', 'Sarlin');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Heikki', 'Linnanen');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Marko', 'Rasku');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Petri', 'Lahtinen');