INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Donald', 'Duck');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Huey', 'Duck');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Dewey', 'Duck');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Louie', 'Duck');