INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (1, 'Donald', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (2, 'Huey', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (3, 'Dewey', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (4, 'Louie', 'Duck');
