CREATE TABLE IF NOT EXISTS PERSON (
    ID INTEGER NOT NULL,
    FIRSTNAME VARCHAR(128) NOT NULL,
    LASTNAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (1, 'Donald', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (2, 'Huey', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (3, 'Dewey', 'Duck');
INSERT INTO PERSON (ID, FIRSTNAME, LASTNAME) VALUES (4, 'Louie', 'Duck');